### ISSUE TITLE
Change Art Work on a Schedule

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/AIArt#3]
### *Some of this may have already been completed.

- ﻿﻿ Remove all GPIO arguments.

-  Add an argument defining the number of seconds before the artwork should be changed. Save that argument to a new class variable called self.seconds_before_artwork_change
-  Add a class variable called self.time_last_image_change = datetime.datetime.now()
-  Update the function def start() to something similar to this:
```python
def start(self) -> None:
    """Starts infinate loop listening to button click. When clicked, it changes the active artwork."""
    while True:
        if (datetime.datetime.now() - self.time_last_image_change).seconds > self.seconds_before_artwork_change:
            self._change_active_artwork()
            self.time_last_image_change = datetime.datetime.now()
```
-  Remove the function def _is_false_negative_click()

### *I have not tried the code above, it's just a hint of how you could change it.

**Comment by jclocks** [comment]
Hello @marshalmiller, I'm an intermediate Python dev and I'd like to give this one a go for Hacktoberfest if that's alright!

**Comment by marshalmiller** [comment]
@jclocks It's all yours!

**Comment by jclocks** [comment]
Thank you! Sorry for the delay here, still working on this, had some stuff come up this week.
Just doublechecking:
"Remove all GPIO arguments."
By this are you basically disabling use of the pushbutton altogether/removing associated code for it in this project? Or are you looking to still have that available as a "feature" of the project?

**Comment by marshalmiller** [comment]
No. I would like to disable that function completely. The original project required a physical button to activate the change. I'm looking to just put it on a timer so that it generates new art every hour or whatever. The original project just had a larger footprint since you needed to house the button with the screen. This would allow a slick wall-mount option.

**Comment by marshalmiller** [comment]
Yes. Thank you. I picked up the tensor flow issues. If you could try to draft something I would very much appreciate it.
